site_name: Website Youtube DL Wiki
theme:
  name: material
  palette:
    scheme: slate # Enables Dark Mode by default!

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - System Diagram: architecture.md
  - Core Modules:
    - YouTube Core Engine: code/youtube_dl.md
    - Downloader Service: code/downloader_service.md
    - Config Manager: code/config.md
  - WebSocket API:
    - Namespaces (Controllers): code/namespaces.md
    - Socket Manager: code/sockets.md
    - Media Info Emit: code/media_info.md