import pydot
import sys
import os

def split_architecture(input_file):
    # Load the main graph (mother graph) generated by pyreverse
    graphs = pydot.graph_from_dot_file(input_file)
    if not graphs:
        print("No graph found!")
        sys.exit(1)

    main_graph = graphs[0]
    nodes = main_graph.get_nodes()
    edges = main_graph.get_edges()

    # Dictionary to group nodes by their module name
    modules = {}

    for node in nodes:
        name = node.get_name().strip('"')

        # Skip Graphviz configuration nodes
        if name in ('node', 'edge', 'graph') or name.startswith('cluster'):
            continue

        # pyreverse names nodes using their full path, e.g., "website_youtube_dl.flask_api.sockets.session_data"
        parts = name.split('.')

        # Extract the main module name (e.g., 'sockets', 'services').
        # Adjust the 'parts[x]' index if your folder structure is different!
        if len(parts) >= 4:
            module_name = parts[3]
        else:
            module_name = 'core'

        if module_name not in modules:
            modules[module_name] = []
        modules[module_name].append(node)

    print(f"Found modules: {list(modules.keys())}")

    # Generate a separate graph for each module
    for mod_name, mod_nodes in modules.items():
        subgraph = pydot.Dot(graph_type='digraph', rankdir='BT', nodesep='0.3', ranksep='0.5')
        node_names = set()

        # Add nodes belonging to the current module
        for n in mod_nodes:
            subgraph.add_node(n)
            node_names.add(n.get_name())

        # Find dependencies (edges) connected to nodes in this module
        for e in edges:
            src = e.get_source()
            dst = e.get_destination()

            if src in node_names or dst in node_names:
                # If the edge connects to a class from ANOTHER module, add it as a simplified, dashed node
                if src not in node_names:
                    label = src.strip('"').split('.')[-1]
                    subgraph.add_node(pydot.Node(src, label=label, shape='box', style='dashed, filled', fillcolor='#f0f0f0'))
                if dst not in node_names:
                    label = dst.strip('"').split('.')[-1]
                    subgraph.add_node(pydot.Node(dst, label=label, shape='box', style='dashed, filled', fillcolor='#f0f0f0'))

                subgraph.add_edge(e)

        # Save and log the output
        output_name = f"classes_{mod_name}.dot"
        subgraph.write_dot(output_name)
        print(f"Generated sub-graph: {output_name}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python split_graph.py <file.dot>")
        sys.exit(1)
    split_architecture(sys.argv[1])